module.exports = [
  { code: "aaa00", name: "Unknown" },
  { code: "efw21", name: "A Little Queen's Huge Crown" },
  { code: "efm01", name: "Abyssal Crown" },
  { code: "efa12", name: "Alabastron" },
  { code: "efw13", name: "Alencinox's Wrath" },
  { code: "efa07", name: "Alexa's Basket" },
  { code: "efk09", name: "Bastion of Perlutia" },
  { code: "efm16", name: "Black Hand of the Goddess" },
  { code: "efr01", name: "Bloodstone" },
  { code: "efm14", name: "Bloody Rose" },
  { code: "efw07", name: "Border Coin" },
  { code: "efh06", name: "Celestine" },
  { code: "efw18", name: "Champion's Trophy" },
  { code: "efm07", name: "Chatty" },
  { code: "efw17", name: "Circus Fantasia" },
  { code: "efw16", name: "Cradle of Life" },
  { code: "efw09", name: "Creation & Destruction" },
  { code: "efm18", name: "Crimson Moon of Nightmares" },
  { code: "efk13", name: "Crown of Glory" },
  { code: "efm13", name: "Dignus Orb" },
  { code: "efh12", name: "Doctor's Bag" },
  { code: "efa16", name: "Double-Edged Decrescent" },
  { code: "efw11", name: "Draco Plate" },
  { code: "efw02", name: "Durandal" },
  { code: "efr12", name: "Dux Noctis" },
  { code: "efk02", name: "Elbris Ritual Sword" },
  { code: "efm02", name: "Etica's Scepter" },
  { code: "efr13", name: "Guiding Light" },
  { code: "efk01", name: "Holy Sacrifice" },
  { code: "efh07", name: "Idol's Cheer" },
  { code: "efr08", name: "Iron Fan" },
  { code: "efw08", name: "Junkyard Dog" },
  { code: "efk07", name: "Justice for All" },
  { code: "efm17", name: "Last Teatime" },
  { code: "efa13", name: "Manica of Control" },
  { code: "ef508", name: "Manifu" },
  { code: "efw14", name: "Merciless Glutton" },
  { code: "efr14", name: "Ms. Confille" },
  { code: "ef503", name: "Cruel Mischief" },
  { code: "efm10", name: "Necro & Undine" },
  { code: "efk06", name: "Noble Oath" },
  { code: "efr06", name: "Otherworldly Machinery" },
  { code: "ef501", name: "Proof of Valor" },
  { code: "efr10", name: "Reingar's Special Drink" },
  { code: "efa01", name: "Rhianna & Luciella" },
  { code: "efk12", name: "Rise of a Monarch" },
  { code: "efh01", name: "Rod of Amaryllis" },
  { code: "efw20", name: "Samsara Prayer Beads" },
  { code: "efa14", name: "Secret Art - Storm Sword" },
  { code: "efa15", name: "Shepherd of the Hollow" },
  { code: "efh02", name: "Shimadra Staff" },
  { code: "efw01", name: "Sigurd Scythe" },
  { code: "efw19", name: "Snow Crystal" },
  { code: "efr02", name: "Song of Stars" },
  { code: "efm11", name: "Spirit's Breath" },
  { code: "efh09", name: "Stella Harpa" },
  { code: "efk08", name: "Sword of Ezera" },
  { code: "ef515", name: "Sword of Holy Light" },
  { code: "efr09", name: "Sword of Judgment" },
  { code: "efm06", name: "Time Matter" },
  { code: "efa09", name: "Torn Sleeve" },
  { code: "efh11", name: "Touch of Rekos" },
  { code: "efw06", name: "Uberius's Tooth" },
  { code: "efh10", name: "Unfading Memories" },
  { code: "efa08", name: "Violet Talisman" },
  { code: "efr15", name: "Wall of Order" },
  { code: "efa02", name: "Wind Rider" },
  { code: "efk04", name: "Adamant Shield" },
  { code: "efr07", name: "Ambrote" },
  { code: "efr11", name: "Andre's Crossbow" },
  { code: "efk03", name: "Aurius" },
  { code: "efm15", name: "Barthez's Orbuculum" },
  { code: "ef401", name: "Card of Small Miracles" },
  { code: "efw10", name: "Crimson Seed" },
  { code: "efa05", name: "Dust Devil" },
  { code: "efw03", name: "El's Fist" },
  { code: "efa04", name: "Elyha's Knife" },
  { code: "efh08", name: "Eternus" },
  { code: "efw15", name: "Flower Shower" },
  { code: "ef411", name: "Golden Cocoa Cookie" },
  { code: "efw04", name: "Hell Cutter" },
  { code: "efk05", name: "Hilag Lance" },
  { code: "efm08", name: "Iela Violin" },
  { code: "efr03", name: "Infinity Basket" },
  { code: "efm04", name: "Kal'adra" },
  { code: "ef402", name: "Love Potion" },
  { code: "efh05", name: "Magaraha's Tome" },
  { code: "ef406", name: "Midnight Bloom" },
  { code: "efa03", name: "Moonlight Dreamblade" },
  { code: "ef410", name: "New Year Cookies" },
  { code: "ef405", name: "One Year of Gratitude" },
  { code: "ef403", name: "Portrait of the Saviors" },
  { code: "efm09", name: "Radiant Forever" },
  { code: "ef404", name: "Rainbow Scale" },
  { code: "efr05", name: "Rosa Hargana" },
  { code: "efa06", name: "Santa Muerte" },
  { code: "efr04", name: "Sashe Ithanes" },
  { code: "efw12", name: "Sepulcrum" },
  { code: "efa10", name: "Shepherds of Chaos" },
  { code: "efa11", name: "Silver Rain" },
  { code: "efm05", name: "Sira-Ren" },
  { code: "ef407", name: "Spooky Solayu Stories" },
  { code: "efk10", name: "Steadfast Gatekeeper" },
  { code: "efw05", name: "Strak Gauntlet" },
  { code: "efm03", name: "Tagehel's Ancient Book" },
  { code: "efm12", name: "Tear of the Desert" },
  { code: "ef414", name: "To a New World" },
  { code: "efh03", name: "Water's Origin" },
  { code: "efh04", name: "Wondrous Potion Vial" },
  { code: "ef418", name: "XVI. The Tower" },
  { code: "ef307", name: "Alsacian Spear" },
  { code: "ef304", name: "Ancient Sheath" },
  { code: "ef314", name: "Aqua Rose" },
  { code: "ef315", name: "Ascending Axe" },
  { code: "ef306", name: "Atma's Portal" },
  { code: "ef318", name: "Butterfly Mandolin" },
  { code: "ef309", name: "Cursed Compass" },
  { code: "ef317", name: "Daydream Joker" },
  { code: "ef312", name: "Devil's Brand" },
  { code: "ef302", name: "Egg of Delusion" },
  { code: "ef319", name: "Envoy's Pipe" },
  { code: "ef316", name: "Exorcist's Tonfa" },
  { code: "ef321", name: "Forest Totem" },
  { code: "ef313", name: "Goblin's Lamp" },
  { code: "ef301", name: "Grail of Blood" },
  { code: "ef308", name: "Labyrinth Cube" },
  { code: "ef311", name: "Mighty Yaksha" },
  { code: "ef322", name: "Oath Key" },
  { code: "ef303", name: "Prophetic Candlestick" },
  { code: "ef305", name: "Ranon's Memorandum" },
  { code: "ef310", name: "Sword of the Morning" },
  { code: "ef320", name: "Timeless Anchor" },
  { code: "ef205", name: "Bloodbead Dagger" },
  { code: "ef201", name: "Deadly Sword" },
  { code: "ef202", name: "Elf's Bow" },
  { code: "ef204", name: "Fairy's Grimoire" },
  { code: "ef206", name: "Firm Shield" },
  { code: "ef203", name: "Staff of Wisdom" },
  { code: "ef104", name: "Biting Wind Star" },
  { code: "ef102", name: "Demon's Pistol" },
  { code: "ef103", name: "Dream Scroll" },
  { code: "ef106", name: "Enhanced Gauntlet" },
  { code: "ef101", name: "Sword of the Sun" },
  { code: "ef105", name: "Venus Orb" },
  { code: "efr16", name: "Unseen Observer"}
]
