module.exports = [
    { code: "c1100", name: "Alencia" },
    { code: "c2042", name: "Ambitious Tywin" },
    { code: "c2019", name: "Apocalypse Ravi" },
    { code: "c1048", name: "Aramintha" },
    { code: "c2007", name: "Arbiter Vildred" },
    { code: "c1015", name: "Baal & Sezan" },
    { code: "c1093", name: "Baiken" },
    { code: "c1053", name: "Basar" },
    { code: "c1071", name: "Bellona" },
    { code: "c2039", name: "Blood Moon Haste" },
    { code: "c2024", name: "Briar Witch Iseria" },
    { code: "c1002", name: "Cecilia" },
    { code: "c1103", name: "Celine" },
    { code: "c1081", name: "Cerise" },
    { code: "c1079", name: "Cermia" },
    { code: "c1027", name: "Charles" },
    { code: "c1009", name: "Charlotte" },
    { code: "c1049", name: "Chloe" },
    { code: "c1101", name: "Choux" },
    { code: "c2012", name: "Dark Corvus" },
    { code: "c2053", name: "Desert Jewel Basar" },
    { code: "c2022", name: "Destina" },
    { code: "c1076", name: "Diene" },
    { code: "c1094", name: "Dizzy" },
    { code: "c1091", name: "Elena" },
    { code: "c1105", name: "Elphelt" },
    { code: "c1108", name: "Ervalen" },
    { code: "c2046", name: "Faithless Lidica" },
    { code: "c2002", name: "Fallen Cecilia" },
    { code: "c1039", name: "Haste" },
    { code: "c5016", name: "Holiday Yufine" },
    { code: "c1024", name: "Iseria" },
    { code: "c2006", name: "Judge Kise" },
    { code: "c1073", name: "Kawerik" },
    { code: "c1023", name: "Kayron" },
    { code: "c1047", name: "Ken" },
    { code: "c1006", name: "Kise" },
    { code: "c1070", name: "Krau" },
    { code: "c1109", name: "Landy" },
    { code: "c2070", name: "Last Rider Krau" },
    { code: "c1046", name: "Lidica" },
    { code: "c1089", name: "Lilias" },
    { code: "c1095", name: "Lilibet" },
    { code: "c2009", name: "Little Queen Charlotte" },
    { code: "c1069", name: "Ludwig" },
    { code: "c1082", name: "Luluca" },
    { code: "c1066", name: "Luna" },
    { code: "c2049", name: "Maid Chloe" },
    { code: "c2047", name: "Martial Artist Ken" },
    { code: "c1096", name: "Melissa" },
    { code: "c1044", name: "Mui" },
    { code: "c1080", name: "Pavel" },
    { code: "c1019", name: "Ravi" },
    { code: "c1090", name: "Ray" },
    { code: "c2074", name: "Remnant Violet" },
    { code: "c1102", name: "Roana" },
    { code: "c1022", name: "Ruele of Light" },
    { code: "c2015", name: "Sage Baal & Sezan" },
    { code: "c5071", name: "Seaside Bellona" },
    { code: "c1038", name: "Sez" },
    { code: "c1072", name: "Sigret" },
    { code: "c2048", name: "Silver Blade Aramintha" },
    { code: "c1092", name: "Sol" },
    { code: "c2038", name: "Specimen Sez" },
    { code: "c2050", name: "Specter Tenebria" },
    { code: "c1067", name: "Tamarinne" },
    { code: "c1050", name: "Tenebria" },
    { code: "c2082", name: "Top Model Luluca" },
    { code: "c1042", name: "Tywin" },
    { code: "c1007", name: "Vildred" },
    { code: "c1074", name: "Violet" },
    { code: "c1088", name: "Vivian" },
    { code: "c1016", name: "Yufine" },
    { code: "c1030", name: "Yuna" },
    { code: "c1083", name: "Zeno" },
    { code: "c1017", name: "Achates" },
    { code: "c1062", name: "Angelica" },
    { code: "c1008", name: "Armin" },
    { code: "c2013", name: "Assassin Cartuja" },
    { code: "c2014", name: "Assassin Cidd" },
    { code: "c2033", name: "Assassin Coli" },
    { code: "c2031", name: "Auxiliary Lots" },
    { code: "c2043", name: "Benevolent Romann" },
    { code: "c2021", name: "Blaze Dingo" },
    { code: "c2011", name: "Blood Blade Karin" },
    { code: "c1013", name: "Cartuja" },
    { code: "c2005", name: "Celestial Mercedes" },
    { code: "c2037", name: "Challenger Dominiel" },
    { code: "c2010", name: "Champion Zerato" },
    { code: "c1014", name: "Cidd" },
    { code: "c1028", name: "Clarissa" },
    { code: "c1033", name: "Coli" },
    { code: "c1012", name: "Corvus" },
    { code: "c2054", name: "Crescent Moon Rin" },
    { code: "c2008", name: "Crimson Armin" },
    { code: "c1036", name: "Crozet" },
    { code: "c1021", name: "Dingo" },
    { code: "c1037", name: "Dominiel" },
    { code: "c2032", name: "Fighter Maya" },
    { code: "c3026", name: "Free Spirit Tieria" },
    { code: "c1087", name: "Furious" },
    { code: "c2035", name: "General Purrgis" },
    { code: "c2018", name: "Guider Aither" },
    { code: "c1011", name: "Karin" },
    { code: "c1086", name: "Khawana" },
    { code: "c1085", name: "Khawazu" },
    { code: "c2028", name: "Kitty Clarissa" },
    { code: "c1107", name: "Kizuna AI" },
    { code: "c1029", name: "Leo" },
    { code: "c1031", name: "Lots" },
    { code: "c1032", name: "Maya" },
    { code: "c1005", name: "Mercedes" },
    { code: "c1035", name: "Purrgis" },
    { code: "c1054", name: "Rin" },
    { code: "c2029", name: "Roaming Warrior Leo" },
    { code: "c1043", name: "Romann" },
    { code: "c1003", name: "Rose" },
    { code: "c1020", name: "Schuri" },
    { code: "c1040", name: "Serila" },
    { code: "c2003", name: "Shadow Rose" },
    { code: "c2017", name: "Shooting Star Achates" },
    { code: "c1004", name: "Silk" },
    { code: "c2062", name: "Sinful Angelica" },
    { code: "c1065", name: "Surin" },
    { code: "c2065", name: "Tempest Surin" },
    { code: "c2036", name: "Troublemaker Crozet" },
    { code: "c2004", name: "Wanderer Silk" },
    { code: "c2020", name: "Watcher Schuri" },
    { code: "c1010", name: "Zerato" },
    { code: "c3043", name: "Adlay" },
    { code: "c5001", name: "Adventurer Ras" },
    { code: "c3105", name: "Ainos" },
    { code: "c3093", name: "Ains" },
    { code: "c1018", name: "Aither" },
    { code: "c3012", name: "Alexa" },
    { code: "c4065", name: "All-Rounder Wanda" },
    { code: "c4042", name: "Angelic Montmorancy" },
    { code: "c3004", name: "Arowell" },
    { code: "c3031", name: "Azalea" },
    { code: "c3006", name: "Bask" },
    { code: "c3095", name: "Batisse" },
    { code: "c3001", name: "Butcher Corps Inquisitor" },
    { code: "c4034", name: "Captain Rikoris" },
    { code: "c3071", name: "Carmainerose" },
    { code: "c3051", name: "Carrot" },
    { code: "c3064", name: "Celeste" },
    { code: "c4001", name: "Chaos Inquisitor" },
    { code: "c4025", name: "Chaos Sect Axe" },
    { code: "c3025", name: "Church of Ilryos Axe" },
    { code: "c4035", name: "Commander Lorina" },
    { code: "c4073", name: "Doll Maker Pearlhorizon" },
    { code: "c3044", name: "Doris" },
    { code: "c3094", name: "Eaton" },
    { code: "c3054", name: "Elson" },
    { code: "c3022", name: "Enott" },
    { code: "c4003", name: "Falconer Kluri" },
    { code: "c3103", name: "Glenn" },
    { code: "c3074", name: "Gloomyrain" },
    { code: "c3101", name: "Godmother" },
    { code: "c3024", name: "Gunther" },
    { code: "c3091", name: "Hataan" },
    { code: "c3041", name: "Hazel" },
    { code: "c3023", name: "Helga" },
    { code: "c3055", name: "Hurado" },
    { code: "c3102", name: "Ian" },
    { code: "c3053", name: "Jecht" },
    { code: "c3052", name: "Jena" },
    { code: "c3011", name: "Judith" },
    { code: "c3084", name: "Kikirat v2" },
    { code: "c3063", name: "Kiris" },
    { code: "c3003", name: "Kluri" },
    { code: "c3092", name: "Lena" },
    { code: "c3035", name: "Lorina" },
    { code: "c4044", name: "Magic Scholar Doris" },
    { code: "c4041", name: "Mascot Hazel" },
    { code: "c4023", name: "Mercenary Helga" },
    { code: "c3014", name: "Mirsa" },
    { code: "c3072", name: "Mistychain" },
    { code: "c3042", name: "Montmorancy" },
    { code: "c3033", name: "Mucacha" },
    { code: "c3061", name: "Nemunas" },
    { code: "c3045", name: "Otillie" },
    { code: "c3073", name: "Pearlhorizon" },
    { code: "c3005", name: "Pyllis" },
    { code: "c1001", name: "Ras" },
    { code: "c3075", name: "Requiemroar" },
    { code: "c4051", name: "Researcher Carrot" },
    { code: "c4013", name: "Righteous Thief Roozid" },
    { code: "c3034", name: "Rikoris" },
    { code: "c3062", name: "Rima" },
    { code: "c3013", name: "Roozid" },
    { code: "c3104", name: "Sonia" },
    { code: "c3015", name: "Sven" },
    { code: "c3032", name: "Taranor Guard" },
    { code: "c3002", name: "Taranor Royal Guard" },
    { code: "c3021", name: "Tieria" },
    { code: "c3065", name: "Wanda" }
  ]
  